// Card theme interface
export interface CardTheme {
  background: string;
  border: string;
  stroke: string;
  ring: string;
  fire: string;
  currStreakNum: string;
  sideNums: string;
  currStreakLabel: string;
  sideLabels: string;
  dates: string;
  excludeDaysLabel: string;
}

// Available color names
export const colorNames = [
  "aliceblue",
  "antiquewhite",
  "aqua",
  "aquamarine",
  "azure",
  "beige",
  "bisque",
  "black",
  "blanchedalmond",
  "blue",
  "blueviolet",
  "brown",
  "burlywood",
  "cadetblue",
  "chartreuse",
  "chocolate",
  "coral",
  "cornflowerblue",
  "cornsilk",
  "crimson",
  "cyan",
  "darkblue",
  "darkcyan",
  "darkgoldenrod",
  "darkgray",
  "darkgreen",
  "darkgrey",
  "darkkhaki",
  "darkmagenta",
  "darkolivegreen",
  "darkorange",
  "darkorchid",
  "darkred",
  "darksalmon",
  "darkseagreen",
  "darkslateblue",
  "darkslategray",
  "darkslategrey",
  "darkturquoise",
  "darkviolet",
  "deeppink",
  "deepskyblue",
  "dimgray",
  "dimgrey",
  "dodgerblue",
  "firebrick",
  "floralwhite",
  "forestgreen",
  "fuchsia",
  "gainsboro",
  "ghostwhite",
  "gold",
  "goldenrod",
  "gray",
  "green",
  "greenyellow",
  "grey",
  "honeydew",
  "hotpink",
  "indianred",
  "indigo",
  "ivory",
  "khaki",
  "lavender",
  "lavenderblush",
  "lawngreen",
  "lemonchiffon",
  "lightblue",
  "lightcoral",
  "lightcyan",
  "lightgoldenrodyellow",
  "lightgray",
  "lightgreen",
  "lightgrey",
  "lightpink",
  "lightsalmon",
  "lightseagreen",
  "lightskyblue",
  "lightslategray",
  "lightslategrey",
  "lightsteelblue",
  "lightyellow",
  "lime",
  "limegreen",
  "linen",
  "magenta",
  "maroon",
  "mediumaquamarine",
  "mediumblue",
  "mediumorchid",
  "mediumpurple",
  "mediumseagreen",
  "mediumslateblue",
  "mediumspringgreen",
  "mediumturquoise",
  "mediumvioletred",
  "midnightblue",
  "mintcream",
  "mistyrose",
  "moccasin",
  "navajowhite",
  "navy",
  "oldlace",
  "olive",
  "olivedrab",
  "orange",
  "orangered",
  "orchid",
  "palegoldenrod",
  "palegreen",
  "paleturquoise",
  "palevioletred",
  "papayawhip",
  "peachpuff",
  "peru",
  "pink",
  "plum",
  "powderblue",
  "purple",
  "rebeccapurple",
  "red",
  "rosybrown",
  "royalblue",
  "saddlebrown",
  "salmon",
  "sandybrown",
  "seagreen",
  "seashell",
  "sienna",
  "silver",
  "skyblue",
  "slateblue",
  "slategray",
  "slategrey",
  "snow",
  "springgreen",
  "steelblue",
  "tan",
  "teal",
  "thistle",
  "tomato",
  "transparent",
  "turquoise",
  "violet",
  "wheat",
  "white",
  "whitesmoke",
  "yellow",
  "yellowgreen",
] as const;

// Card themes collection
export const cardThemes: Record<string, CardTheme> = {
  default: {
    background: "#FFFEFE",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#FB8C00",
    fire: "#FB8C00",
    currStreakNum: "#151515",
    sideNums: "#151515",
    currStreakLabel: "#FB8C00",
    sideLabels: "#151515",
    dates: "#464646",
    excludeDaysLabel: "#464646",
  },
  dark: {
    background: "#151515",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#FB8C00",
    fire: "#FB8C00",
    currStreakNum: "#FEFEFE",
    sideNums: "#FEFEFE",
    currStreakLabel: "#FB8C00",
    sideLabels: "#FEFEFE",
    dates: "#9E9E9E",
    excludeDaysLabel: "#9E9E9E",
  },
  highcontrast: {
    background: "#000000",
    border: "#BEBEBE",
    stroke: "#BEBEBE",
    ring: "#FB8C00",
    fire: "#FB8C00",
    currStreakNum: "#FFFFFF",
    sideNums: "#FFFFFF",
    currStreakLabel: "#FB8C00",
    sideLabels: "#FFFFFF",
    dates: "#C5C5C5",
    excludeDaysLabel: "#C5C5C5",
  },
  transparent: {
    background: "#0000",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#006AFF",
    fire: "#006AFF",
    currStreakNum: "#0579C3",
    sideNums: "#006AFF",
    currStreakLabel: "#0579C3",
    sideLabels: "#006AFF",
    dates: "#417E87",
    excludeDaysLabel: "#417E87",
  },
  radical: {
    background: "#141321",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#FE428E",
    fire: "#FE428E",
    currStreakNum: "#F8D847",
    sideNums: "#FE428E",
    currStreakLabel: "#F8D847",
    sideLabels: "#FE428E",
    dates: "#A9FEF7",
    excludeDaysLabel: "#A9FEF7",
  },
  merko: {
    background: "#0A0F0B",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#ABD200",
    fire: "#ABD200",
    currStreakNum: "#B7D364",
    sideNums: "#ABD200",
    currStreakLabel: "#B7D364",
    sideLabels: "#ABD200",
    dates: "#68B587",
    excludeDaysLabel: "#68B587",
  },
  gruvbox: {
    background: "#282828",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#FABD2F",
    fire: "#FABD2F",
    currStreakNum: "#FE8019",
    sideNums: "#FABD2F",
    currStreakLabel: "#FE8019",
    sideLabels: "#FABD2F",
    dates: "#8EC07C",
    excludeDaysLabel: "#8EC07C",
  },
  tokyonight: {
    background: "#1A1B27",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#70A5FD",
    fire: "#70A5FD",
    currStreakNum: "#BF91F3",
    sideNums: "#70A5FD",
    currStreakLabel: "#BF91F3",
    sideLabels: "#70A5FD",
    dates: "#38BDAE",
    excludeDaysLabel: "#38BDAE",
  },
  onedark: {
    background: "#282C34",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#E4BF7A",
    fire: "#E4BF7A",
    currStreakNum: "#8EB573",
    sideNums: "#E4BF7A",
    currStreakLabel: "#8EB573",
    sideLabels: "#E4BF7A",
    dates: "#DF6D74",
    excludeDaysLabel: "#DF6D74",
  },
  dracula: {
    background: "#282A36",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#FF6E96",
    fire: "#FF6E96",
    currStreakNum: "#79DAFA",
    sideNums: "#FF6E96",
    currStreakLabel: "#79DAFA",
    sideLabels: "#FF6E96",
    dates: "#F8F8F2",
    excludeDaysLabel: "#F8F8F2",
  },
  monokai: {
    background: "#272822",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#EB1F6A",
    fire: "#EB1F6A",
    currStreakNum: "#E28905",
    sideNums: "#EB1F6A",
    currStreakLabel: "#E28905",
    sideLabels: "#EB1F6A",
    dates: "#F1F1EB",
    excludeDaysLabel: "#F1F1EB",
  },
  vue: {
    background: "#FFFEFE",
    border: "#A8A8A8",
    stroke: "#A8A8A8",
    ring: "#41B883",
    fire: "#41B883",
    currStreakNum: "#41B883",
    sideNums: "#41B883",
    currStreakLabel: "#41B883",
    sideLabels: "#41B883",
    dates: "#273849",
    excludeDaysLabel: "#273849",
  },
  "vue-dark": {
    background: "#273849",
    border: "#E4E2E2",
    stroke: "#E4E2E2",
    ring: "#41B883",
    fire: "#41B883",
    currStreakNum: "#41B883",
    sideNums: "#41B883",
    currStreakLabel: "#41B883",
    sideLabels: "#41B883",
    dates: "#FFFEFE",
    excludeDaysLabel: "#FFFEFE",
  },
  github: {
    background: "#FFFFFF",
    border: "#D0D7DE",
    stroke: "#D0D7DE",
    ring: "#0969DA",
    fire: "#0969DA",
    currStreakNum: "#24292F",
    sideNums: "#24292F",
    currStreakLabel: "#0969DA",
    sideLabels: "#24292F",
    dates: "#656D76",
    excludeDaysLabel: "#656D76",
  },
  "github-dark": {
    background: "#0D1117",
    border: "#30363D",
    stroke: "#30363D",
    ring: "#58A6FF",
    fire: "#58A6FF",
    currStreakNum: "#F0F6FC",
    sideNums: "#F0F6FC",
    currStreakLabel: "#58A6FF",
    sideLabels: "#F0F6FC",
    dates: "#8B949E",
    excludeDaysLabel: "#8B949E",
  },
};

// Get theme names
export const getThemeNames = (): string[] => Object.keys(cardThemes);

// Get theme by name
export const getTheme = (themeName: string): CardTheme => {
  return cardThemes[themeName] || cardThemes.default;
};

// Check if theme exists
export const themeExists = (themeName: string): boolean => {
  return themeName in cardThemes;
};
